/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 29-May-2023 19:54:50
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 15
 * Denominator Length  : 15
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 15;
const real64_T NUM[15] = {
  0.0004105477255015,-0.003003219133398,  0.01032297501517, -0.02227712233896,
    0.03342792220862, -0.03527592979123,  0.02290719997265,                 0,
   -0.02290719997265,  0.03527592979123, -0.03342792220862,  0.02227712233896,
   -0.01032297501517, 0.003003219133398,-0.0004105477255015
};
const int DL = 15;
const real64_T DEN[15] = {
                   1,    -10.7896060212,    55.14464192171,   -176.8375029822,
      397.3155224271,   -661.3882738072,    840.9948837077,   -829.7013401024,
      638.1714734386,   -380.8472611872,    173.6197684063,   -58.64792344901,
      13.88322781081,   -2.062904015084,   0.1453020044313
};
