/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 29-May-2023 19:48:40
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 9
 * Denominator Length  : 9
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 9;
const real64_T NUM[9] = {
  0.0001138593246702,-0.0008234575723542, 0.002673146682517,-0.005103216101481,
   0.006279335333334,-0.005103216101481, 0.002673146682517,-0.0008234575723542,
  0.0001138593246702
};
const int DL = 9;
const real64_T DEN[9] = {
                   1,   -7.837703444626,    26.89396425939,   -52.76934620224,
       64.7571234475,   -50.89468472375,    25.01708453415,   -7.031739106093,
     0.8653012360476
};
