/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 23-May-2023 10:07:21
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 7;
const real64_T NUM[7] = {
  9.874431124812e-05,-0.0005917814163382, 0.001478427567612,-0.001970780924863,
   0.001478427567612,-0.0005917814163382,9.874431124812e-05
};
const int DL = 7;
const real64_T DEN[7] = {
                   1,     -5.9712594209,    14.85670983502,   -19.71424136905,
      14.71505932901,   -5.857936786346,     0.97166841227
};
