/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 29-May-2023 19:53:11
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 11
 * Denominator Length  : 11
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 11;
const real64_T NUM[11] = {
  0.0002555640014017,-0.001497230193305, 0.003882225652321, -0.00566641917043,
    0.00439726382702,-8.673617379884e-19, -0.00439726382702,  0.00566641917043,
  -0.003882225652321, 0.001497230193305,-0.0002555640014017
};
const int DL = 11;
const real64_T DEN[11] = {
                   1,   -8.998072035518,    36.69897645812,   -89.33624498186,
      143.7357069066,   -159.7090223648,    124.1129129412,   -66.61070673014,
      23.62976899605,   -5.003639340849,   0.4803206245102
};
