/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 29-May-2023 20:16:57
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 5;
const real64_T NUM[5] = {
  0.0001176623637818,-0.0003975350537905,0.0005597453856586,-0.0003975350537905,
  0.0001176623637818
};
const int DL = 5;
const real64_T DEN[5] = {
                   1,   -3.987400506041,    5.962752535884,   -3.963300569769,
     0.9879485963381
};
