/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 29-May-2023 19:51:09
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 9
 * Denominator Length  : 9
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 9;
const real64_T NUM[9] = {
  0.0001758855780071,-0.001002480529608, 0.002657566121453,-0.004422028372704,
   0.005182114410934,-0.004422028372704, 0.002657566121453,-0.001002480529608,
  0.0001758855780071
};
const int DL = 9;
const real64_T DEN[9] = {
                   1,   -7.640536469345,    25.60287460499,   -49.14465026524,
      59.10222693403,    -45.6008037045,    22.04372558647,   -6.104187607152,
     0.7413509730557
};
