/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 21-May-2023 21:22:13
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 5;
const real64_T NUM[5] = {
  9.964750069948e-05,-0.000398282822749,0.0005972707625114,-0.000398282822749,
  9.964750069948e-05
};
const int DL = 5;
const real64_T DEN[5] = {
                   1,   -3.991395786471,      5.9742243566,   -3.974261260511,
     0.9914326905011
};
